export default [{
    year: "1974",
    event: '成立宣德實業公司',
    text: "",
    tag: "成立與擴展",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "1978",
    event: '成立華新橡膠工業股份有限公司',
    text: "專營醫用橡膠手套生產與銷售",
    tag: "成立與擴展",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "1988",
    event: '成立 泰國華新橡膠工業股份有限公司M.R.I.泰國廠',
    text: "",
    tag: "成立與擴展",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "1989",
    event: '華新橡膠公司通過GMP',
    text: "為臺灣早期之醫療器材製造商",
    tag: "認證與獲獎",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "1995",
    event: '成立上海華新醫材有限公司',
    text: "專營醫用橡膠手套生產與銷售",
    tag: "成立與擴展",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "1996",
    event: '華新橡膠公司榮獲國際金球獎',
    text: "成為最佳產品出口廠商",
    tag: "認證與獲獎",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "1999",
    event: '華新集團併購專營傷口敷料的三禾田公司',
    text: "專營醫用橡膠手套生產與銷售",
    tag: "成立與擴展",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "2001",
    event: '三禾田遷入臺灣田中廠',
    text: "同年華新橡膠工業股份有限公司英文更名為 Modern Healthcare Corp",
    tag: "轉型與變遷",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "2001",
    event: '臺灣廠獲得TUV、ISO 9001、N46001 、CE認證',
    text: "",
    tag: "認證與獲獎",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "2003",
    event: '宣德實業公司轉型成為宣德醫材科技股份有限公司',
    text: "專營防護口罩的產銷。開始發展自有品牌，鞏固國內市場，開拓海外市場",
    tag: "轉型與變遷",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "2006",
    event: '創新研發產品「鑽石型超立體口罩」榮獲多項獎牌',
    text: "在美國匹茲堡、瑞士日內瓦、臺灣臺北、中國北京、德國紐倫堡、韓國首爾等國際發明展中大放異彩，為企業及國家爭光",
    tag: "認證與獲獎",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "2007",
    event: '榮獲「國家發明創作獎 」，榮獲總統頒發「創新產品獎 」',
    text: "",
    tag: "認證與獲獎",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "2008",
    event: '「長效型香芬鑽石型立體口罩」榮獲2008臺灣精品獎',
    text: "同年亦榮獲美國匹茲堡國際發明展金牌與特別獎",
    tag: "認證與獲獎",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "2009",
    event: '「鑽石型立體口罩」榮獲「國家生技醫療品質獎」',
    text: "並獲總統接見嘉勉",
    tag: "認證與獲獎",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "2012",
    event: '獨立經營發展',
    text: "為更快速因應市場變化及有效掌握商機，華新集團進化為臺灣、泰國及中國等三個獨立經營發展的醫材集團",
    tag: "轉型與變遷",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "2014",
    event: '創新發明屢獲肯定',
    text: "「口腔口罩」榮獲東京天才發明展金牌、「 氣密鑽石型口罩 」榮獲臺北國際發明展金牌獎",
    tag: "認證與獲獎",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "2015",
    event: 'Mask創意生活館通過評鑑',
    text: "亞洲首座口罩觀光工廠「Mask創意生活館」於4月通過評鑑，同年7月通過進階評鑑升級為「優良觀光工廠」",
    tag: "成立與擴展",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "2015",
    event: '「氣密鑽石型口罩」榮獲2015臺灣精品獎',
    text: "同年「迪士尼系列口罩」為臺灣地區唯一圖像正式授權上市",
    tag: "認證與獲獎",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "2016",
    event: '集團新廠5月動土典禮，興建新廠辦大樓',
    text: "新廠大樓於2019年落成啟用",
    tag: "轉型與變遷",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "2017",
    event: '董事長鄭永柱獲頒WDIC國際傑出發明家',
    text: "",
    tag: "認證與獲獎",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "2018",
    event: '「氣密式鑽石型防霾口罩」榮獲2018臺灣精品獎',
    text: "同年Mask 創意生活館在7月通過「觀光工廠及優良觀光工廠續評」",
    tag: "認證與獲獎",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "2020",
    event: '參與台灣口罩國家隊',
    text: "",
    tag: "社會責任",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},
{
    year: "2020",
    event: '台中營業處成立',
    text: "熔噴過濾布新產線啟用口罩設備材料整廠輸出台中營業處成立",
    tag: "成立與擴展",
    img: 'https://motex-elearning.github.io/course/onBoarding/img/timeline/bg.png',
},

];